#ifndef CONFIG_H
#define CONFIG_H

#define NAV_BUTTON_PIN 35
#define ENT_BUTTON_PIN 0

#define SCANNER_SDA 21
#define SCANNER_SCL 22
#define PN532_IRQ 32
#define PN532_RST 33

#define ICRS_SSID "YOUR SSID"
#define ICRS_PASSWORD "YOUR WIFI PASSWORD"
#define ICRS_SERVER_HOST "YOUR SERVER IP"
#define ICRS_SERVER_PORT 8000 // Your server endpoint port

#define ICRS_SERVER_USERNAME "YOUR USERNAME"
#define ICRS_SERVER_PASSWORD "YOUR PASSWORD"

#endif